// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "VisionVoice",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "VisionVoice",
            targets: ["AppModule"],
            bundleIdentifier: "com.mushudev.PrismLens",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.indigo),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "PrismLens needs the camera to recognize objects and place AR overlays."),
                .photoLibrary(purposeString: "photo"),
                .photoLibraryAdd(purposeString: "Add photo")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ],
    swiftLanguageVersions: [.version("6")]
)
